### ISSUE TITLE
Release app-explorer 1.5

### ISSUE THREAD

**Issue by ComLock** [enonic/app-explorer#290]
- [x] Publish binary to https://repo.enonic.com/public/com/enonic/app/explorer/1.5.0
- [x] Point https://developer.enonic.com/docs/explorer/ to 1.5.0 https://enonic.com/admin/tool/com.enonic.app.contentstudio/main#/dev-portal/edit/08b7c305-6bb8-427f-bafc-9992e201d203
- [x] Create release with changelog on github? https://github.com/enonic/app-explorer/tags https://github.com/enonic/app-explorer/releases/tag/v1.5.0
- [x] Changelog on market https://enonic.com/admin/site/preview/market/draft/enonic-market/vendors/enonic/explorer
- [x] Publish on market https://enonic.com/admin/tool/com.enonic.app.contentstudio/main#/market/edit/d9dd7151-c3c6-4d2e-bc83-9880573cc5e4
- [x] Publish on community slack
- [x] Publish on disquss

Documentation
https://developer.enonic.com/docs/explorer/1.5.0
