### ISSUE TITLE
Explorer 2.0 release

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#628]
- [x] Test using webcrawler collector
- [x] Release and tag 2.0.0
- [x] Release notes on Github (change log)
- [x] Update documentation on dev portal
- [x] Release starter-collector and docs
- [x] Update Enonic market

Moved to separate task #869

**Comment by ComLock** [comment]
Changelog:

* Added GraphQL search 🎉
* Added DocumentTypes
* Added Documents search page
* Improved search on homepage and under interfaces
* Simplified Interfaces
* Improved Synonyms (language, stemming)
* Removed Schema page: Fields and Field values (use DocumentTypes)
* Removed lib-explorer.search function (use GraphQL)
* Added data migrations from v1 -> v2 that runs at first start
* Code converted to TypeScript
* Code test coverage improved
* Improved Collector class
* Removed deprecated functions collector.register & unregister
