### ISSUE TITLE
Webcrawler improvements

### ISSUE THREAD

**Issue by ComLock** [enonic/app-explorer#894]
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/app-explorer/issues/899
- [ ] https://github.com/enonic/app-explorer/issues/898
- [ ] https://github.com/enonic/app-explorer/issues/897
- [ ] https://github.com/enonic/app-explorer/issues/896
- [ ] https://github.com/enonic/app-explorer/issues/895
- [ ] https://github.com/enonic/app-explorer/issues/900
- [ ] https://github.com/enonic/app-explorer/issues/901
```
